### ISSUE TITLE
feature_request(css3_colors): convert to CSS3 colors

### ISSUE THREAD

**Issue by Kristinita** [zhouyuexie/ColorConvert#1]
### 1. Summary

It would be nice, if would be possible convert from any format to [**CSS3 color names**](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value).

Example:

    from HEX to CSS3 color names:

+ input — `#4b0082`
+ output — `indigo`

### 2. Argumentation

CSS3 color names — format for humans, not for bots. I don't remember HEX, RGB and HSL of red color, but I remember, that it `red`.

Situations, where I need CSS3 color names:

1. [**css-to-stylus**](https://www.npmjs.com/package/css-to-stylus-converter) (I'm sure, that another tools also) convert from CSS3 to HEX.
1. I can copy CSS from some sites → I'm don't understand, which color I copy, because I don't know HEX/RGB/HSL codes. I need convert to CSS3 color names, that understand what colors it is.

Thanks.

**Comment by obetame** [comment]
This is a good idea, I will add this feature`(HEX -> Css_Color_Name)` in the next version.

I did not consider this feature before because the css color name is not much, only 147.

**Comment by obetame** [comment]
@Kristinita The latest version 2.1.0 has been released, but it cannot be installed using package control at present.

so if you really want to experience this new feature, I suggest you directly clone this library into your sublime package directory(menu->preferences->browse packages) and restart the sublime.

Thank you for using my plugin.

**Comment by Kristinita** [comment]
@zhouyuexie ,

**Status: :exclamation: Another problem**

### 1. Summary

It would be nice, if CSS3 color names will be in lowercase.

### 2. Argumentation

[**Default Sublime Text CSS3 syntax**](https://github.com/sublimehq/Packages/tree/master/CSS) highlight only lowercase CSS3 color names.

### 3. Steps to reproduce

I select `#ff0000` → I run command `color_convert_hex_to_name`.

### 4. Expected behavior

`red` highlight.

![Expected](https://i.imgur.com/4l9xPDk.png)

### 5. Actual behavior

`Red` doesn't highlight.

![Red](https://i.imgur.com/79Ud09L.png)

Thanks.

**Comment by Kristinita** [comment]
@zhouyuexie , notes:

1. You can make prereleases of your Sublime Text packages, [**example**](https://github.com/weituotian/md_numbered_headers/releases).
1. Perhaps, for you my article will be useful — [**Fastest way to add new version of your Sublime Text package**](https://kristinita.ru/IT-articles/Fastest-way-to-add-new-version-of-Sublime-Text-3-package).

Thanks.

**Comment by obetame** [comment]
@Kristinita 

Thank you for your feedback and guidance.

This is my first sublime package and I haven't been exposed to this kind of release process before, and I'm sorry if this bug has caused some of your other problems.

I will try to fix this issue and understand the release mechanism as soon as possible.

**Comment by Kristinita** [comment]
@zhouyuexie , ping.

Can you make CSS color names lowercase?

Thanks.

**Comment by obetame** [comment]
@Kristinita you mean?

1. Hex->colorName, the colorName is lowercase.
2. make all colorNames lowercase in the file.

and if someone needs colorName capitalization, then corresponds to the whole name capitalization or hum capitalization?

**Comment by Kristinita** [comment]
@zhouyuexie , **answers**:

> Hex->colorName, the colorName is lowercase.

Yes, I meant it.

> make all colorNames lowercase in the file.

Also, it would be nice if would be possible convert all HEX → colorName for file.

> and if someone needs colorName capitalization, then corresponds to the whole name capitalization or hum capitalization?

I do not know the arguments why capitalization is needed. my opinion — if any user argues for the need for capitalization, then we can think about it.

Thanks.

**Comment by obetame** [comment]
@Kristinita The capitalization configuration takes into account some people’s habits, so I kept it.

A 2.2.0 version has just been updated, and colorName can be controlled by capitalization configuration. 

**The version adding full file conversion: Hex->colorName**

*Capitalization defaults to false, so you can leave it alone.*

Hope you will like it.😝

**Comment by Kristinita** [comment]
@zhouyuexie ,

**Status: :broken_heart: Partially fixed**

### 1. Summary

HEX colors, that contains 3 symbols after hash, doesn't convert to CSS color names.

### 2. Configuration

Example `SashaConvert.css` file:

```css
body {
    color: #fff;
    color: #ffffff;
    color: #f00;
    color: #ff0000;
}

```

### 3. Steps to reproduce

I run command `color_convert_all_hex_to_name`.

### 4. Expected behavior

```css
body {
    color: white;
    color: white;
    color: red;
    color: red;
}
```

### 5. Actual behavior

```css
body {
    color: #fff;
    color: white;
    color: #f00;
    color: red;
}

```

Thanks.

**Comment by Kristinita** [comment]
@zhouyuexie ,

**Status: :exclamation: Another problem**

### 1. Summary

[**ARGB**](https://en.wikipedia.org/wiki/RGBA_color_space#ARGB_(word-order)) colors incorrect convert.

### 2. Configuration

Example `SashaARGB.css` file:

```css
body {
    color: #f0808077;
}

```

### 3. Steps to reproduce

I run command `color_convert_all_hex_to_name`.

### 4. Expected behavior

No convert ARGB:

```css
body {
    color: #f0808077;
}

```

### 5. Actual behavior

Bug:

```css
body {
    color: lightcoral77;
}

```

Thanks.

**Comment by obetame** [comment]
@Kristinita It has been confirmed that these problems do exist, I will immediately repair it.

Will notify you the first time after the repair is completed, thank you.

**Comment by obetame** [comment]
@Kristinita the new version v2.3.0 is publish.

I hope that these repairs will meet your expectations.

**Comment by Kristinita** [comment]
@zhouyuexie ,

**Status: :exclamation: Another problem**

### 1. Summary

ARGB colors convert to CSS color names. This should not be.

### 2. Argumentation

First 2 symbols in ARGB — transparency.

Example: `#80FFFFFF` — 50% transparency for white color

More details:

+ [**ARGB colors in Android**](https://coderwall.com/p/dedqca/argb-colors-in-android)

### 3. Data

Configuration, steps to reproduce and expected behavior [**as in previous section**](https://github.com/zhouyuexie/ColorConvert/issues/1#issuecomment-386821148).

`f0` in `#f0808077` — transparency for `#808077` color, not for `lightcoral`.

### 4. Actual behavior

```css
body {
    color: lightcoral;
}
```

Thanks.

**Comment by obetame** [comment]
@Kristinita Hex containing transparency is not the same format in android and css, sorry to ignore this detail.

the new version v2.3.1 is publish.

**Comment by obetame** [comment]
@Kristinita The new versions 2.3.1 add config 'is_android', you should change is to 'true'.

the package.io website is break, so may need to wait for a while

**Comment by Kristinita** [comment]
**❔ Question**

> Hex containing transparency is not the same format in android and css

Where I can read about it in more details?

Thanks.

**Comment by obetame** [comment]
### css

Syntax like `#RRGGBB[AA]`, more info: [color_value](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgb()_and_rgba())

### android

Syntax like `#[AA]RRGGBB`, more info: [android color](https://developer.android.com/guide/topics/resources/more-resources#Color)

**Comment by Kristinita** [comment]
@zhouyuexie,

**Status: :x: Still doesn't work for me**

**Example**:

If user wrote `#ff000080`, it means that he want `red` color with 50% transparency, not just `red`. `#ff000080` not must convert to `red`, because in `red` no transparency.

Thanks.

**Comment by obetame** [comment]
My fault, I thought you need this conversion....

Will notify you the first time after the repair is completed.

**Comment by obetame** [comment]
@Kristinita Version 2.3.3 has been released. 

Major increase loss_transparent setting, does not allow the loss of transparency in ` hex_to_colorname` conversion by default.

**Comment by obetame** [comment]
@Kristinita Version 2.3.3 has been released. 

Major increase loss_transparent setting, does not allow the loss of transparency in ` hex_to_colorname` conversion by default.

**Comment by Kristinita** [comment]
**Status: :heavy_check_mark: Fixed for me**

Thanks.
